name: AutomatedTesting

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      - name: Node Setup
        uses: actions/setup-node@v2
      - name: install npm packages
        run : "npm install"
      # run all Jest tests
      - name: Jest tests
        run: "npm run unitTest"
      # and run all Cypress tests
      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: "npm start"
          browser: chrome
     
